# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1804"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
  end
end
